const photos = [
    { src: './img/photos/spring_1.png', feel: './img/happy.png', comment: 'This is a very nice place!', date: '2019-03-13', time: '09:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_2.png', feel: './img/glad.png', comment: '', date: '2019-03-15', time: '10:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_3.png', feel: './img/happy.png', comment: 'This is a very nice place!', date: '2019-04-13', time: '12:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_4.png', feel: './img/happy.png', comment: '', date: '2019-04-17', time: '16:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_5.png', feel: '', comment: 'This is a very nice place!', date: '2019-05-12', time: '17:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_6.png', feel: '', comment: 'This is a very nice place!', date: '2019-05-17', time: '20:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_7.png', feel: './img/glad.png', comment: '', date: '2019-05-12', time: '21:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_8.png', feel: './img/happy.png', comment: 'This is a very nice place!', date: '2019-04-18', time: '15:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_9.png', feel: '', comment: '', date: '2019-05-19', time: '15:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_10.png', feel: '', comment: '', date: '2019-03-19', time: '09:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_11.png', feel: '', comment: '', date: '2019-03-19', time: '08:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_12.png', feel: '', comment: '', date: '2019-04-19', time: '09:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_13.png', feel: '', comment: '', date: '2019-04-19', time: '12:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_14.png', feel: '', comment: '', date: '2019-04-19', time: '16:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_15.png', feel: '', comment: '', date: '2019-05-19', time: '22:00', season: 'spring', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/spring_16.png', feel: '', comment: '', date: '2019-05-19', time: '24:00', season: 'spring', musicSrc: './media/testMusic.mp3' },

    { src: './img/photos/summer_1.png', feel: '', comment: 'This is a very nice place!', date: '2019-06-20', time: '16:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_2.png', feel: './img/glad.png', comment: 'This is a very nice place!', date: '2019-06-20', time: '17:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_3.png', feel: '', comment: 'This is a very nice place!', date: '2019-06-12', time: '09:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_4.png', feel: '', comment: 'This is a very nice place!', date: '2019-06-13', time: '10:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_5.png', feel: '', comment: '', date: '2019-07-18', time: '11:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_6.png', feel: './img/glad.png', comment: 'This is a very nice place!', date: '2019-07-12', time: '12:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_7.png', feel: './img/glad.png', comment: 'This is a very nice place!', date: '2019-08-13', time: '14:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_8.png', feel: '', comment: '', date: '2019-08-21', time: '15:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_9.png', feel: '', comment: 'This is a very nice place!', date: '2019-08-26', time: '15:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_10.png', feel: '', comment: 'This is a very nice place!', date: '2019-07-26', time: '17:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_11.png', feel: '', comment: 'This is a very nice place!', date: '2019-07-26', time: '10:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_12.png', feel: '', comment: 'This is a very nice place!', date: '2019-06-26', time: '22:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_13.png', feel: '', comment: 'This is a very nice place!', date: '2019-06-26', time: '24:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_14.png', feel: '', comment: 'This is a very nice place!', date: '2019-06-26', time: '19:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_15.png', feel: '', comment: 'This is a very nice place!', date: '2019-07-26', time: '7:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
    { src: './img/photos/summer_16.png', feel: '', comment: 'This is a very nice place!', date: '2019-08-26', time: '8:00', season: 'summer', musicSrc: './media/testMusic2.mp3' },
   
    { src: './img/photos/autumn_1.png', feel: './img/glad.png', comment: '', date: '2019-09-25', time: '16:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/autumn_2.png', feel: './img/glad.png', comment: 'This is a very nice place!', date: '2019-09-21', time: '21:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/autumn_3.png', feel: './img/glad.png', comment: 'This is a very nice place!', date: '2019-09-02', time: '20:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/autumn_4.png', feel: './img/glad.png', comment: '', date: '2019-10-04', time: '19:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/autumn_5.png', feel: './img/glad.png', comment: '', date: '2019-10-02', time: '18:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/autumn_6.png', feel: './img/glad.png', comment: '', date: '2019-11-03', time: '13:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/autumn_7.png', feel: './img/glad.png', comment: '', date: '2019-11-06', time: '14:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/autumn_8.png', feel: './img/glad.png', comment: '', date: '2019-11-07', time: '09:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/autumn_9.png', feel: './img/glad.png', comment: '', date: '2019-09-09', time: '10:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/autumn_10.png', feel: './img/glad.png', comment: '', date: '2019-10-09', time: '17:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/autumn_11.png', feel: './img/glad.png', comment: '', date: '2019-11-09', time: '22:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/autumn_12.png', feel: './img/glad.png', comment: '', date: '2019-11-09', time: '16:00', season: 'autumn', musicSrc: './media/testMusic.mp3' },
    
    { src: './img/photos/winter_1.jpg', feel: './img/glad.png', comment: '', date: '2019-12-01', time: '11:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_2.jpg', feel: './img/glad.png', comment: '', date: '2019-12-05', time: '12:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_3.jpg', feel: './img/glad.png', comment: '', date: '2019-12-12', time: '16:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_4.png', feel: './img/glad.png', comment: '', date: '2019-12-14', time: '18:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_5.png', feel: './img/glad.png', comment: '', date: '2019-01-18', time: '13:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_6.png', feel: './img/glad.png', comment: '', date: '2019-01-21', time: '15:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_7.png', feel: './img/glad.png', comment: '', date: '2019-01-26', time: '10:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_8.png', feel: './img/glad.png', comment: '', date: '2019-02-01', time: '21:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_9.png', feel: './img/glad.png', comment: '', date: '2019-02-04', time: '20:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_10.png', feel: './img/glad.png', comment: '', date: '2019-02-04', time: '09:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_11.png', feel: './img/glad.png', comment: '', date: '2019-02-04', time: '10:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_12.png', feel: './img/glad.png', comment: '', date: '2019-01-04', time: '06:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_13.png', feel: './img/glad.png', comment: '', date: '2019-01-04', time: '04:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_14.png', feel: './img/glad.png', comment: '', date: '2019-12-04', time: '18:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_15.png', feel: './img/glad.png', comment: '', date: '2019-12-04', time: '15:00', season: 'winter', musicSrc: './media/testMusic.mp3' },
    { src: './img/photos/winter_16.png', feel: './img/glad.png', comment: '', date: '2019-02-04', time: '21:00', season: 'winter', musicSrc: './media/testMusic.mp3' }
]